# Generated by Django 6.0.3 on 2026-05-08 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='gymServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('icon', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=50)),
                ('popular', models.BooleanField(default=False)),
                ('period', models.CharField(blank=True, default='', max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=50)),
                ('img_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPlanFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=30)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.membershipplans')),
            ],
        ),
        migrations.CreateModel(
            name='serviceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.features')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.gymservices')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('service', 'feature'), name='unique_service_feature')],
            },
        ),
        migrations.CreateModel(
            name='TrainerSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.specialties')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.trainers')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('trainer', 'specialty'), name='unique_trainer_specialty')],
            },
        ),
    ]
