# Generated by Django 6.0.3 on 2026-03-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_features_gymservices_servicefeature'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='servicefeature',
            constraint=models.UniqueConstraint(fields=('service', 'feature'), name='unique_service_feature'),
        ),
    ]
