# Generated by Django 6.0.3 on 2026-03-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_membershipplans_membershipplanfeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplans',
            name='period',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
